// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  FunctionDeclaration = 2,
  Identifier = 3,
  FormalParameters = 4,
  FunctionBody = 5,
  VariableDeclaration = 6,
  Assignment = 7,
  Expression = 8,
  Number = 9,
  String = 10,
  Unary = 11,
  Binary = 12,
  SubExpression = 13,
  FunctionCall = 14,
  ActualParameters = 15,
  ReturnStatement = 16
