// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {scope, definition, use} from "../src/props"
const spec_identifier = {__proto__:null,func:70, var:84, return:108}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQYQPOOOOQO'#C`'#C`OOQO'#Cf'#CfObQPO'#C_OgQPO'#CtOOQO'#C}'#C}OlQPO'#C}OOQO'#Cv'#CvQYQPOOOOQO'#Ca'#CaOqQPO,58yOOQO'#Cu'#CuOOQO,59`,59`OOQO,59i,59iOOQO-E6t-E6tOvQPO'#DQOOQO'#Cb'#CbO!OQPO1G.eOOQO'#Cc'#CcOOQO,59l,59lO!TQPO,59lO!]QPO7+$PO!kQPO'#CwO!pQPO1G/WOOQO1G/W1G/WO!kQPO'#CeO!xQPO'#ChO#vQPO'#CoO#{QPO'#CgOOQO'#Cs'#CsO$QQPO'#CrO$cQPO'#DVOOQO'#Cx'#CxO$hQPO'#CdO$vQPO<<GkOOQO,59c,59cOOQO-E6u-E6uOOQO7+$r7+$rOOQO,59P,59PO${QPO'#DcOOQO'#Cq'#CqOOQO,59Z,59ZO$QQPO,59RO$QQPO'#ClO%tQPO,59^O$QQPO'#CnOOQO'#Ci'#CiOOQO,59q,59qOOQO-E6v-E6vOOQOAN=VAN=VO%{QPO,59}OOQO,59},59}O&VQPO1G.mOOQO,59W,59WO$QQPO,59XO$QQPO,59XO$QQPO,59XO&^QPO,59YO$QQPO'#CyO&eQPO1G/iOOQO1G/i1G/iOOQO1G.s1G.sO'bQPO1G.sO'lQPO1G.sOOQO1G.t1G.tO'vQPO,59eOOQO-E6w-E6wOOQO7+%T7+%T",
  stateData: "(Q~OpOSPOS~OsPOzQO~OrXO~OrZO~O!X]O~Ou_O~OrbOwcO~OxeO~OvfOwhO~OrjOzQO!WmO!YWP~OrbO~OvfOwuO~OudX{[X|[X}[X!O[X!P[X!Q[X!R[X!S[X!T[X!U[X!X[Xv[Xw[X~OuwO~O{zO~O^!OO_!OOrjOu}O|{O~O!X!PO~OrjOzQO!WmO!YWX~O!Y!RO~Ow!TO~P$QO{!YO|!XO}!WO!O!WO!P!XO!Q!YO!R!YO!S!YO!T!YO!U!YO~O!Xfa~P%SOv![Ow!^O~P%SO!XZi~P%SOw!bO~P%SOv![Ow!eO~O}!WO!O!WO{ai!Qai!Rai!Sai!Tai!Uai!Xaivaiwai~O|ai!Pai~P&mO|!XO!P!XO~P&mOvmawma~P%SO",
  goto: "%o!WPPP!X!]!a!d!g!p!s!w!s#P#`PP#T#T#T#{$[$i!s$l$p$t$w$}%T%ZPPP%aPP%ePPPP%hPPPPPPPPPPP%lTTOWTROWRYRRaYQd_QsfRviRreToeqSSOWTieqSleqc!Onwz{}!W!X!Y![Q|nQ!SwQ!UzQ!V{Q!Z}Q!_!WQ!`!XQ!a!YR!c![Soeqc!Onwz{}!W!X!Y![gkenqwz{}!W!X!Y![RykTneqTUOWR[SQWOR^WQgdRtgQqeR!QqQ!]!SR!d!]TVOWR`YTpeqRxk",
  nodeNames: "⚠ Comment Program FunctionDeclaration Function FunctionDefinition FormalParameters LocalVariableDefinition FunctionBody VariableDeclaration Var Assignment VariableUse Expression Number String Unary Binary SubExpression FunctionCall FunctionUse ActualParameters ReturnStatement Return GlobalVariableDeclaration GlobalVariableDefinition",
  maxTerm: 56,
  nodeProps: [
    [scope, 2,"",3,"definitions=FormalParameters,uses=FunctionBody"],
    [definition, -3,5,7,25,""],
    [use, -2,12,20,""]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "&f~RfXY!gYZ!g]^!gpq!grs!xst#mxy$Uyz$Zz{$`{|$e|}$j}!O$o!P!Q$t!Q![$y!]!^%R!^!_%W!_!`%m!`!a%r!c!}&P#T#o&P#o#p&[#q#r&a~!lSp~XY!gYZ!g]^!gpq!g~!{TOY#[Zr#[s;'S#[;'S;=`#g<%lO#[~#_Prs#b~#gO_~~#jP;=`<%l#[~#rSP~OY#mZ;'S#m;'S;=`$O<%lO#m~$RP;=`<%l#m~$ZOu~~$`Ow~~$eO}~~$jO!P~~$oOv~~$tO|~~$yO!O~~%OP^~!Q![$y~%WO!X~~%]Q!Q~!_!`%c!`!a%h~%hO!T~~%mO!S~~%rO{~~%wP!R~!_!`%z~&PO!U~~&UQr~!c!}&P#T#o&P~&aOx~~&fO!Y~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 34, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
