// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,func:52, var:66, return:92}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(vQYQPOOOOQO'#Cu'#CuObQPO'#CuOOQO'#Cm'#CmQYQPOOOgQPO'#CbOlQPO'#C^OOQO,59a,59aOOQO-E6k-E6kOOQO,58|,58|OqQPO,58xOvQPO'#CwOOQO'#C`'#C`O!OQPO1G.dOOQO,59c,59cO!TQPO,59cO!]QPO7+$OO!kQPO'#CnO!pQPO1G.}OOQO1G.}1G.}O!xQPO'#CjO#QQPO'#C|OOQO'#Co'#CoO#VQPO'#CaO#eQPO'#ClO#vQPO<<GjOOQO,59Y,59YOOQO-E6l-E6lOOQO7+$i7+$iO#{QPO'#DZOOQO'#Ck'#CkOOQO,59U,59UO#eQPO,58}OOQO,59h,59hOOQO-E6m-E6mO#eQPO'#CgO$tQPO'#CdO#eQPO'#CiO%RQPO'#DPOOQO'#DP'#DPOOQO,59W,59WOOQOAN=UAN=UOOQO,59u,59uO&PQPO,59uOOQO1G.i1G.iOOQO,59R,59RO#eQPO,59SO#eQPO,59SO#eQPO,59SO&XQPO,59TO#eQPO'#CpO&`QPO1G/aOOQO1G/a1G/aOOQO1G.n1G.nO']QPO1G.nO'gQPO1G.nOOQO1G.o1G.oOOQO,59[,59[OOQO-E6n-E6nOOQO7+${7+${",
  stateData: "'q~OgOShOS~OjUOqTO~O!PVO~ORXO~ORYO~OlZO~OR_On^O~Oo`O~OmaOncO~ORdOqTO!OhO!QTP~ORjO~OmaOnlO~OlmOrpO~O!PqO~ORdOqTO!OhO!QTX~ORvOXwOYwOluOtsO~O!QyO~OnzO~P#eOr!QOt!POu!OOv!OOw!POx!QOy!QOz!QO{!QO|!QO~O!PWXmWXnWX~P$SOlmOrsXtsXusXvsXwsXxsXysXzsX{sX|sX!PsXmsXnsX~Om!SOn!UO~On!YO~P$SOm!SOn!]O~Ou!OOv!OOr[ix[iy[iz[i{[i|[i!P[im[in[i~Ot[iw[i~P&hOt!POw!PO~P&hO",
  goto: "$m!OPP!PP!T!W!Z!_!cPP!o!o!o!z#Z!_#_#e#k#qPPPP#wP#{PPPP$OPP$SPPPPPPPPP$iTPOSR]YRi`SQOSTe`gQxhQ{mQ|pR!Z!Scwhmpsu!O!P!Q!SSe`gcwhmpsu!O!P!Q!STodvQSORWSQb_RkbQg`RrgQ!T{R![!TTROSR[YTf`gWthmp!SQ}sQ!RuQ!V!OQ!W!PR!X!QTndv",
  nodeNames: "⚠ Program FunctionDeclaration Identifier FormalParameters FunctionBody VariableDeclaration Assignment Expression Number String Unary Binary SubExpression FunctionCall ActualParameters ReturnStatement",
  maxTerm: 48,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "&f~RfXY!gYZ!g]^!gpq!grs!xst#mxy$Uyz$Zz{$`{|$e|}$j}!O$o!P!Q$t!Q![$y!]!^%R!^!_%W!_!`%m!`!a%r!c!}&P#T#o&P#o#p&[#q#r&a~!lSg~XY!gYZ!g]^!gpq!g~!{TOY#[Zr#[s;'S#[;'S;=`#g<%lO#[~#_Prs#b~#gOY~~#jP;=`<%l#[~#rSh~OY#mZ;'S#m;'S;=`$O<%lO#m~$RP;=`<%l#m~$ZOl~~$`On~~$eOu~~$jOw~~$oOm~~$tOt~~$yOv~~%OPX~!Q![$y~%WO!P~~%]Qx~!_!`%c!`!a%h~%hO{~~%mOz~~%rOr~~%wPy~!_!`%z~&PO|~~&UQR~!c!}&P#T#o&P~&aOo~~&fO!Q~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
