// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {scope} from "../src/scope"
import {definition} from "../src/definition"
import {use} from "../src/use"
const spec_identifier = {__proto__:null,func:84, var:96, return:120}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*nQYQPOOOOQO'#C`'#C`OOQO'#Ci'#CiObQPO'#C_OgQPO'#C{OOQO'#DU'#DUOOQO'#C}'#C}QYQPOOOOQO'#Ca'#CaOlQPO,58yOOQO'#C|'#C|OqQPO,59gOOQO-E6{-E6{OvQPO'#DXOOQO'#Cc'#CcO!OQPO'#CbOOQO1G.e1G.eOOQO1G/R1G/ROOQO'#Cd'#CdOOQO,59s,59sO!TQPO,59sOOQO'#Cf'#CfO!]QPO'#CeOOQO,58|,58|O!kQPO'#DOO!pQPO1G/_OOQO1G/_1G/_O!xQPO'#ChO!}QPO'#ClO#{QPO'#CuO$QQPO'#CkOOQO'#Cy'#CyO$VQPO'#CxO$hQPO'#CgOOQO'#DP'#DPO!]QPO,59POOQO'#Cz'#CzOOQO,59P,59POOQO,59j,59jOOQO-E6|-E6|OOQO7+$y7+$yOOQO'#Cj'#CjOOQO,59S,59SO$mQPO'#DiOOQO'#Cw'#CwOOQO,59a,59aO$VQPO,59VO$VQPO'#CpO%fQPO,59dOOQO'#Cs'#CsO$VQPO'#CrOOQO'#Cm'#CmOOQO,59R,59ROOQO-E6}-E6}OOQO1G.k1G.kO%mQPO,5:TOOQO,5:T,5:TO%wQPO1G.qOOQO,59[,59[O$VQPO,59]O$VQPO,59]O$VQPO,59]O&OQPO,59^O$VQPO'#DQO&VQPO1G/oOOQO1G/o1G/oOOQO1G.w1G.wO'SQPO1G.wO'^QPO1G.wOOQO'#Ct'#CtOOQO1G.x1G.xO'hQPO,59lOOQO-E7O-E7OOOQO7+%Z7+%Z",
  stateData: "'r~OwOSPOS~OzPO!QQO~OyWO~OyYO~O|]O~O!_aO~OybO!OcO~O!PeO~O}hO!OjO~OylO!QQO!^oO!`tO~OybO~O}hO!OxO~OyyO~O|jX!R`X!S`X!T`X!U`X!V`X!W`X!X`X!Y`X!Z`X![`X!_`X}`X!O`X~O|{O~O!R!OO~Ob!TOc!TOylO|!RO!S!PO~O!_!UO~O!O!YO~P$VO!R!_O!S!^O!T!]O!U!]O!V!^O!W!_O!X!_O!Y!_O!Z!_O![!_O~O!_la~P$tO}!aO!O!cO~P$tO!__i~P$tO!O!gO~P$tO}!aO!O!kO~O!T!]O!U!]O!Rei!Wei!Xei!Yei!Zei![ei!_ei}ei!Oei~O!Sei!Vei~P&_O!S!^O!V!^O~P&_O}ta!Ota~P$tO",
  goto: "&]!^PPP!_!c!g!j!m!p!v!y!|#Q#U#^#Q#a#pPP#e#e#e$]$h$k$z%X#Q%[%`!_%f%i%o%u%{PPP&RPP&VPPPPPPPPPPPPPPP&YTTOVTROVRXRR`XR_XQd]RvhRg_Rf_TrfsTqfsSSOVTkfsRzkSnfsc!Tp{!O!P!S!]!^!_!aQ!QpQ!X{Q!Z!OQ![!PQ!`!SQ!d!]Q!e!^Q!f!_R!i!ac!Sp{!O!P!S!]!^!_!aR!h!`Sqfsc!Tp{!O!P!S!]!^!_!agmfps{!O!P!S!]!^!_!aR}mTpfsQufR!WsRZSQVOR[VQidRwiQsfR!VsQ!b!XR!j!bTUOVR^XR|m",
  nodeNames: "⚠ Comment Program FunctionDeclaration Function FunctionDefinition FunctionScope FormalParameters ParameterDefinition Block OpenBrace Statement LocalVariableDeclaration Var LocalVariableDefinition Assignment VariableUse Expression Number String Unary Binary SubExpression OpenParen CloseParen FunctionCall FunctionUse ActualParameters ReturnStatement Return CloseBrace GlobalVariableDeclaration GlobalVariableDefinition",
  maxTerm: 62,
  nodeProps: [
    [scope, -3,2,6,9,""],
    [definition, -3,5,8,32,"wholeScope",14,"redefines,overridePrevious"],
    ["closedBy", 10,"CloseBrace",23,"CloseParen"],
    [use, -2,16,26,""],
    ["openedBy", 24,"OpenParen",30,"OpenBrace"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "&i~RfXY!gYZ!g]^!gpq!grs!xst#mxy$Uyz$Zz{$`{|$e|}$j}!O$o!P!Q$t!Q![$y!]!^%R!^!_%W!_!`%m!`!a%r!c!}&P#T#o&P#o#p&_#q#r&d~!lSw~XY!gYZ!g]^!gpq!g~!{TOY#[Zr#[s;'S#[;'S;=`#g<%lO#[~#_Prs#b~#gOc~~#jP;=`<%l#[~#rSP~OY#mZ;'S#m;'S;=`$O<%lO#m~$RP;=`<%l#m~$ZO|~~$`O!O~~$eO!T~~$jO!V~~$oO}~~$tO!S~~$yO!U~~%OPb~!Q![$y~%WO!_~~%]Q!W~!_!`%c!`!a%h~%hO!Z~~%mO!Y~~%rO!R~~%wP!X~!_!`%z~&PO![~~&URy~!Q![&P!c!}&P#T#o&P~&dO!P~~&iO!`~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 41, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
